// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RawDataSource is an autogenerated mock type for the RawDataSource type
type RawDataSource struct {
	mock.Mock
}

// GetDataPath provides a mock function with given fields: basePath, specName
func (_m *RawDataSource) GetDataPath(basePath string, specName string) []string {
	ret := _m.Called(basePath, specName)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string, string) []string); ok {
		r0 = rf(basePath, specName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// GetSpecPath provides a mock function with given fields: basePath
func (_m *RawDataSource) GetSpecPath(basePath string) []string {
	ret := _m.Called(basePath)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(basePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
