// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	model "clover-data-processor/app/model"

	mock "github.com/stretchr/testify/mock"
)

// DataRepository is an autogenerated mock type for the DataRepository type
type DataRepository struct {
	mock.Mock
}

// CheckTableExists provides a mock function with given fields: tableName
func (_m *DataRepository) CheckTableExists(tableName string) bool {
	ret := _m.Called(tableName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(tableName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CreateTable provides a mock function with given fields: spec
func (_m *DataRepository) CreateTable(spec *model.Spec) error {
	ret := _m.Called(spec)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Spec) error); ok {
		r0 = rf(spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: spec, records
func (_m *DataRepository) Insert(spec *model.Spec, records []*model.Record) error {
	ret := _m.Called(spec, records)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Spec, []*model.Record) error); ok {
		r0 = rf(spec, records)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
